---
apiVersion: v1
kind: Pod
metadata:
  name: three-containers
  labels:
    run: busybox
  annotations:
spec:
  restartPolicy: Never
  runtimeClassName: kata-cc
  containers:
    - name: busybox
      image: "mcr.microsoft.com/aks/e2e/library-busybox:master.220314.1-linux-amd64"
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
    - name: mariner-cli
      image: "mcr.microsoft.com/cbl-mariner/base/azure-cli:2"
    - name: acoustics-baketools
      image: "mcr.microsoft.com/acoustics/baketools:2022.1.Linux"
      securityContext:
        allowPrivilegeEscalation: false
