---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-volume
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/my-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume-claim
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: persistent
  labels:
    run: busybox
  annotations:
spec:
  restartPolicy: Never
  runtimeClassName: kata-cc
  containers:
    - name: busybox
      image: "mcr.microsoft.com/aks/e2e/library-busybox:master.220314.1-linux-amd64"
      securityContext:
        readOnlyRootFilesystem: true
      volumeMounts:
        - mountPath: /busy1
          name: data
        - mountPath: /my-volume
          name: my-pod-volume
        - mountPath: /dev/ttyS0
          name: dev-ttys0
  volumes:
    - name: data
      emptyDir: {}
    - name: my-pod-volume
      persistentVolumeClaim:
        claimName: my-volume-claim
    - name: dev-ttys0
      hostPath:
        path: /dev/ttyS0
