---
apiVersion: v1
kind: Pod
metadata:
  name: spark
spec:
  restartPolicy: Never
  runtimeClassName: kata-cc
  containers:
    - name: spark
      image: "mcr.microsoft.com/mmlspark/spark2.4:v4_mini"
