---
apiVersion: v1
kind: ReplicationController
metadata:
  name: cassandra
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      runtimeClassName: kata-cc
      containers:
        - name: cassandra
          image: "gcr.io/google-samples/cassandra:v13"
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: CASSANDRA_SEED_PROVIDER
              value: io.k8s.cassandra.KubernetesSeedProvider
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: "0.5"
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
          command:
            - /run.sh
      volumes:
        - name: data
          emptyDir: {}
